version: '3.9'
services:
  lapizzajip-admin-app:
    container_name: lapizzajip-admin-app
    networks:
      - vis_network
    volumes:
      - shared:/app/wwwroot/uploads
    command: chmod 777 /app/wwwroot/uploads/
    restart: always
    environment:
      - "ASPNETCORE_ENVIRONMENT=PRODUCTION"
      - "ASPNETCORE_HTTP_PORTS=8080;5005"
      - "ASPNETCORE_URLS=http://+:8080;http://+:5005"
      - "WebAppUri:http://localhost:5120/"
      - "ConnectionStrings:BaseDbContext=Server=172.17.0.1; Port=5432; Database=LapizzajipDb; User Id=postgres; Password=12345678;"
      - "ConnectionStrings:IdentityContext=Server=172.17.0.1; Port=5432; Database=LapizzajipAdminDb; User Id=postgres; Password=12345678;"